import os

DATA_PATH = 'danbooru2020_64x64'
DATASET_SIZE = len(os.listdir(DATA_PATH))

IMAGE_SIDE = 64
PRIOR_DIM = 100

CLIP = 0.01
INIT_STD = 0.02
LR = 0.00005

EPOCH_COUNT = 3
BATCH_SIZE = 16
BATCH_DIVISOR = 1
DISCRIMINATOR_LEARNING_REPEATS = 5

MINIBATCH_SIZE = BATCH_SIZE // BATCH_DIVISOR
EPOCH_LEN = int(DATASET_SIZE / (BATCH_SIZE * (DISCRIMINATOR_LEARNING_REPEATS + 1)))